### ISSUE TITLE
Undefined constant in updateOrderStatus method

### ISSUE THREAD

**Issue by andersonba** [konduto/php-sdk#3]
```
Fatal error: Undefined constant 'Konduto\Models\STATUS_APPROVED' in /app/vendor/konduto/sdk/src/Core/Konduto.php on line 144
```

**Comment by adri0** [comment]
Thank you again, @andersonba 
This problem is happening when you don't use the Order class in your current program (commonly happening when using the method updateOrderStatus) so the autoloader does not import the file containing these constants.
I'll correct this problem and hopefully release a new version (v1.4.0) by the end of the day. It will be shipping also your pull request.
There is a [v2.0.0](https://github.com/konduto/php-sdk/tree/v2-beta) in the oven, it will be released in the following weeks. Its api is very similar to the v1, but not backwards-compatible. The sdk v1 will be still supported indefinitely.

**Comment by andersonba** [comment]
Thanks for the answer, @adri0!
Great job! I'm excitedly waiting for new versions.

**Comment by adri0** [comment]
v1.4.0 fixes it
